baseURL = 'http://commandlineawesome.com/'
languageCode = 'en-us'
title = 'Command Line Awesome'

[Params]
	description = "Command Line Awesome!"
	[Params.Terminal]
	scheme = "Afterglow"
	# scheme choices from here: https://gogh-co.github.io/Gogh/

	userName = "cla"
	pcName = "yourComp"
	workDir = "workspace"
	profile = "info.txt"

	# Note: speed at which text is displayed on the terminal
	# Note: if set to 0, typing animation will be disabled
	# Note:
	# Note: if you want to enable Mathjax, you need to set it to 0
	# Note: and set "math: true" at front matter in your Markdown file
	ps1Delay = 0 # prompt speed : [userName]@[pcName]:~/$ , [userName]@[pcName]:~/[workDir]$
	stdoutDelay = 0 # stdout speed : [description] , files in Params.Tree
	commandDelay = 50 # command speed : cd [workDir] , cat [profile] , tree ./[folderName]/

	# terminalDelay = 20 : deprecated

	# Note: speed at which text is displayed on the activity pages
	# Note: if set to 0, typing animation will be disabled
	# Note:
	# Note: if you want to enable Mathjax, you need to set it to 0
	# Note: and set "math: true" at front matter in your Markdown file
	titleDelay = 0 # title speed : "title" in front matter
	contentDelay = 0 # content speed : content in .md file

	# activityDelay = 5 : deprecated

	# description = "/description.md"
	description = """

	Recent years have seen a lot of great innovation and
	iteration of command line tools. Check out these
	sweet new tools you can use.

	"""

	# Note: If you want to use a Markdown file, you can use the following
	# description = "/description.md"
	# Note: and put the description.md in /content/description.md

	[Params.Tree]
	use = true
	folderName = "sweet_tools"
	# Note: ["ACTIVITY", "URL or PATH TO YOUR MARKDOWN FILE"]
	files = [
		["Replacements For Old Standards", "replacements.md"],
		["New Utilities", "new_utilities.md"],
		# ["Python", "https://www.example.com/"],
		# ["Go", "https://golang.org/"],
		# ["Hugo", "/post/some-activity.md"],
		# ["Docker", "/post/some-activity.md"],
	]
